pipeline:
  ssh:
    image: appleboy/drone-ssh
    secrets: [ ssh_host, ssh_username, ssh_password, irisaumurl, irisidmurl, irisevmurl, irisntmurl, irisappkey, irisappsecret, irisenv, irisappdomain, irisinboundservice, irisinboundsecret, irisuserid, irisuserpwd, irisfromtn, iristotn, iriscalleeid ]
    envs: [ irisaumurl, irisidmurl, irisevmurl, irisntmurl, irisappkey, irisappsecret, irisenv, irisappdomain, irisinboundservice, irisinboundsecret, irisuserid, irisuserpwd, irisfromtn, iristotn, iriscalleeid ]
    port: 4222
    script: 
    - cd harish
    - rm -rf IrisSDK
     - export IRISAUMURL=$IRISAUMURL
     - echo $PATH
     - echo $IRISAUMURL
