pipeline:
  ssh:
    image: appleboy/drone-ssh
    secrets: [ ssh_host, ssh_username, ssh_password, irisaumurl, irisidmurl, irisevmurl, irisntmurl, irisappkey, irisappsecret, irisenv, irisappdomain, irisinboundservice, irisinboundsecret, irisuserid, irisuserpwd, irisfromtn, iristotn, iriscalleeid ]
    envs: [ irisaumurl, irisidmurl, irisevmurl, irisntmurl, irisappkey, irisappsecret, irisenv, irisappdomain, irisinboundservice, irisinboundsecret, irisuserid, irisuserpwd, irisfromtn, iristotn, iriscalleeid ]
    port: 4222
    script: 
    - cd harish
    - rm -rf IrisSDK
     - export IRISAUMURL=$IRISAUMURL
      - export IRISIDMURL=${IRISIDMURL} 
      - export IRISEVMURL=$${IRISEVMURL}
      - export IRISNTMURL=$${IRISNTMURL}
      - export IRISAPPKEY=$IRISAPPKEY 
      - export IRISAPPSECRET=$${IRISAPPSECRET}
      - export IRISENV=$${IRISENV} 
      - export IRISAPPDOMAIN=$${IRISAPPDOMAIN} 
      - export IRISINBOUNDSERVICE=$${IRISINBOUNDSERVICE} 
      - export IRISINBOUNDSECRET=$${IRISINBOUNDSECRET} 
      - export IRISUSERID=$${IRISUSERID}
      - export IRISUSERPWD=$${IRISUSERPWD} 
      - export IRISFROMTN=$${IRISFROMTN} 
      - export IRISTOTN=$${IRISTOTN} 
      - export IRISCALLEEID=$${IRISCALLEEID}  
      - echo $IRISAUMURL
    - git clone https://github.com/harishgupta01/IrisSDK
    - cd IrisSDK
    - /usr/local/bin/pod install
    - xcodebuild test -workspace IrisRtcSdk.xcworkspace  -scheme IrisRtcSdk  -destination 'platform=iOS Simulator,name=iPhone X,OS=11.4'  -only-testing:IrisRtcSdkTests/IrisRtcConnectionTest 
